---
- name: Install easy-rsa and create keys
  hosts: all
  vars:
    easyrsa_dest: "/home/stweise/git/ansible-clientcert-nginx/build"
    easyrsa_dn: "cn_only"
    easyrsa_req_country: "US"
    easyrsa_req_province: "California"
    easyrsa_req_city: "San Francisco"
    easyrsa_req_org: "Copyleft Certificate Co"
    easyrsa_req_email: "me@example.net"
    easyrsa_req_ou: "My Organizational Unit"
    easyrsa_req_cn: "ChangeMe"
    easyrsa_keysize: 2048
    easyrsa_digest: "sha256"
    easyrsa_clients:
      - name: client1
      - name: client2
      - name: client3
#    easyrsa_revoked_clients:
#      - name: client1
#      - name: client2
#      - name: client3

  roles:
    - ansible-easyrsa
