---
- name: Install easy-rsa and create keys
  hosts: all
  #  become: true
  vars:
    easyrsa_dest: "/home/stweise/git/ansible-clientcert-nginx/build"
    easyrsa_dn: "cn_only"
    easyrsa_req_country: "US"
    easyrsa_req_province: "California"
    easyrsa_req_city: "San Francisco"
    easyrsa_req_org: "Copyleft Certificate Co"
    easyrsa_req_email: "me@example.net"
    easyrsa_req_ou: "My Organizational Unit"
    easyrsa_req_cn: "ChangeMe"
    easyrsa_keysize: 2048
    easyrsa_digest: "sha256"
    easyrsa_clients:
      - name: client1
      - name: client2
      - name: client3
#    easyrsa_revoked_clients:
#      - name: client1
#      - name: client2
#      - name: client3
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 443
        server_name: localhost
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
              autoindex: false
          http_demo_conf: false
  roles:
    - ansible-easyrsa
      #    - nginxinc.nginx
